"""empty message

Revision ID: 16a1ca12999e
Revises: e3ba2267b72a
Create Date: 2020-06-19 23:41:44.284224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a1ca12999e'
down_revision = 'e3ba2267b72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'event_ts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('event_ts', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
