"""empty message

Revision ID: 5694469c873a
Revises: 8c6da430e649
Create Date: 2020-05-31 15:00:28.611434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5694469c873a'
down_revision = '8c6da430e649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_user', table_name='message')
    op.drop_column('message', 'message')
    op.drop_column('message', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.VARCHAR(length=120), nullable=True))
    op.add_column('message', sa.Column('message', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_message_user', 'message', ['user'], unique=False)
    # ### end Alembic commands ###
