"""empty message

Revision ID: 7d5b0d5f010f
Revises: 5694469c873a
Create Date: 2020-05-31 15:27:10.295342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5b0d5f010f'
down_revision = '5694469c873a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_message_user'), 'message', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_user'), table_name='message')
    op.drop_column('message', 'user')
    # ### end Alembic commands ###
