"""empty message

Revision ID: ac5497f6f469
Revises: 7d5b0d5f010f
Create Date: 2020-05-31 15:27:33.805519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5497f6f469'
down_revision = '7d5b0d5f010f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'message')
    # ### end Alembic commands ###
