"""empty message

Revision ID: c00d8af94dde
Revises: ac5497f6f469
Create Date: 2020-05-31 15:58:00.893519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c00d8af94dde'
down_revision = 'ac5497f6f469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created', sa.DateTime(), nullable=False))
    op.alter_column('message', 'message',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('message', 'user',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_index(op.f('ix_message_created'), 'message', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_created'), table_name='message')
    op.alter_column('message', 'user',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('message', 'message',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('message', 'created')
    # ### end Alembic commands ###
